x-yaml-anchors:  # create anchors "&something" that can be referenced using "*something"
  base: &base
    extends:
      file: ./docker/common.yaml
      service: x11_base
      # service: x11_gpu  # use this service if you want to use nvidia GPU
    volumes:
      - ./config:/config:Z

services:
  bash:  # this service can be used to open a shell in the ROS2 environment
    <<: [*base]  # add elements of 'x-yaml-anchors.base'
    profiles: [optional]  # avoid starting this service when 'compose up'
    command: bash --rcfile /etc/bash.bashrc
  compile:
    <<: *base
    environment:  # remove annoying warning of setuptools
      - PYTHONWARNINGS=ignore:::setuptools.command.easy_install
    command: 'colcon --log-base /dev/null build --symlink-install --event-handlers event_log- log-'
  compile_with_log:
    <<: *base
    environment:  # remove annoying warning of setuptools
      - PYTHONWARNINGS=ignore:::setuptools.command.easy_install
    command: 'colcon build --symlink-install'
  # bash:
  #   <<: *base
  #   command: 'bash --rcfile /etc/bash.bashrc'